require "add.plugins" -- this has to come first
require "add.opts"

require "add.mason"
require "add.mason-lspconfig"
require "add.lspconfig"

-- require "add.cmp"
require "add.comment"
require "add.fidget"
require "add.flash"
require "add.gitsigns"
require "add.harpoon"
require "add.highlight"
require "add.indentline"
require "add.keymap"
require "add.mini-completion"
require "add.mini-files"
require "add.mini-icons"
require "add.mini-sessions"
require "add.mini-starter"
require "add.mini-surround"
require "add.neoscroll"
require "add.statusline"
require "add.telescope"
require "add.toggleterm"
require "add.treesitter"
require "add.twilight"
